version: "3.0"
services:
  nlp-transfer:
    build:
      context: .
    container_name: nlp-transfer
    image: jupyter-image-custom2
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - ../:/usr/src/nlp-transfer
    command: sh -c "
      cd ../../usr/src/nlp-transfer
      && jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"
